### ISSUE TITLE
CD pipeline doesn't wait for deployment (error instead)

### ISSUE THREAD

**Issue by CGHoussem** [Azure/arc-cicd-demo-src#20]
Hello, 

Everytime the CD pipeline is ran manually or automatically triggered by the CI pipeline, I get an error on the "**Wait for changes to be applied**" task ("**wait for the deployment completion**" job to be specific)

![image](https://user-images.githubusercontent.com/18559408/171830186-a4ae6ebf-59bb-48bb-80a1-7e42cdd383b9.png)

Here is the output logged into the agent's console:
```
============================================================================== 
Task         : Wait for deployment completion
Description  : Invoke a REST API as a part of your pipeline.
Version      : 1.198.0
Author       : Microsoft Corporation
Help URL     : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/http-rest-api
============================================================================== 
2022-06-03T08:56:54.7618625Z PATCH https://dev.azure.com/REDACTED/REDACTED/_apis/git/repositories/arc-cicd-demo-gitops/pullRequests/9/properties?api-version=6.0
Request body: [
  {
    "op": "add",
    "path": "/callback-task-id",
    "from": null,
    "value": "{\"taskid\":\"6f2d1337-9ed3-578f-60ac-e83280f1bf3d\", \"jobid\":\"736cfeee-0e1e-576a-9966-266cc2920b0a\", \"planurl\":\"https://dev.azure.com/REDACTED/\",  \"planid\":\"607710ba-7a67-47d6-b381-24f8e5ceb42a\", \"projectid\":\"bb51bca6-9deb-4c65-9d53-8a7028050369\", \"pr_num\":\"9\"}"
  }
]
				Response Code: 0
				Response: An error was encountered while processing request. Exception: {"$id":"1","innerException":null,"message":"TF401019: The Git repository with name or identifier arc-cicd-demo-gitops does not exist or you do not have permissions for the operation you are attempting.","typeName":"Microsoft.TeamFoundation.Git.Server.GitRepositoryNotFoundException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitRepositoryNotFoundException","errorCode":0,"eventId":3000}
Exception Message: The remote server returned an error: (404) Not Found. (type WebException)
```

As you have may noticed, I have changed the changed the api-version from **6.0-preview.1** to the stable version **6.0** (I get the  same issue on the **6.0-preview.1** version).

I am also sure that the arc-cicd-demo-gitops repository exists and I have FULL permissions on my Build Service User
<img width="755" alt="image" src="https://user-images.githubusercontent.com/18559408/171829917-846452e2-e54e-4936-a0f2-afcd73d720ac.png">

**Comment by eedorenko** [comment]
Go to `Pipelines/Settings` and switch off `Protect access to repositories in YAML pipelines` option.
<img width="669" alt="Screen Shot 2022-06-03 at 11 03 47 AM" src="https://user-images.githubusercontent.com/20337555/171921162-b51e4627-db56-4178-b720-0e6205340ffc.png">

**Comment by CGHoussem** [comment]
Thank you @eedorenko 
The issue has been resolved 👍
