### ISSUE TITLE
An error occurred while loading the YAML build pipeline.

### ISSUE THREAD

**Issue by nitinkansal1984** [Azure/arc-cicd-demo-src#9]
I was unable to run CD pipeline. Please help !
![image](https://user-images.githubusercontent.com/31030410/124353347-8fd50300-dc23-11eb-96f7-5ec6cf9b9cf3.png)

**Comment by nitinkansal1984** [comment]
@bjcmit @tcare Please help. I need to showcase this to one of the customer ASAP

**Comment by nitinkansal1984** [comment]
Now I am getting below error
/.pipelines/az-vote-cd-pipeline.yaml (Line: 6, Col: 17): Pipeline Resource az-vote-ci Input Must be Valid.

**Comment by bjcmit** [comment]
@nitinkansal1984 The CD pipeline depends on the CI pipeline. Did the CI pipeline complete successfully?

**Comment by nitinkansal1984** [comment]
Yes that is completed successfully and image pushed to acr.

**Comment by bjcmit** [comment]
Did you name the application CI pipeline "arc-cicd-demo-src CI"?

**Comment by nitinkansal1984** [comment]
yes @bjcmit the application CI pipeline name is "arc-cicd-demo-src CI". Below is the screenshot.

![image](https://user-images.githubusercontent.com/31030410/124375069-b6477c80-dcbd-11eb-9ee1-683517cbcbe0.png)

**Comment by nitinkansal1984** [comment]
Failing to run CD pipeline.
![image](https://user-images.githubusercontent.com/31030410/124375106-f1e24680-dcbd-11eb-9ddc-12ef7ed15def.png)

**Comment by nitinkansal1984** [comment]
I removed everything and followed the steps again. I am getting below error,

![image](https://user-images.githubusercontent.com/31030410/124375869-dda04880-dcc1-11eb-83a8-9186c5cd6c91.png)

**Comment by nitinkansal1984** [comment]
![image](https://user-images.githubusercontent.com/31030410/124377189-4d193680-dcc8-11eb-9c29-bf3afc2ef52e.png)

**Comment by nitinkansal1984** [comment]
@eedorenko I am just waiting for this one to be approved and merged so that I can then do implement the same in my test environment. Thanks !
